### ISSUE TITLE
Is anyone using this?

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/bagit-ro#3]
This looks like really useful work - is it still being maintained? Anybody using it for real?

**Comment by stain** [comment]
Yes, bagit-ro is been used by the [Big Data Bags](https://static.aminer.org/pdf/fa/bigdata2016/BigD418.pdf) in the NIH [BDDS](http://bd2k.ini.usc.edu/tools/) project for large-scale genomics.  

See also the [bdbag](https://github.com/ini-bdds/bdbag) tools:

> The bdbag utilities are a collection of software programs for working with BagIt packages that conform the BDDS Bagit and BDDS Bagit/RO profiles.

**Comment by stain** [comment]
BTW, I've invited you to the [ResearchObject Gitter chat](https://gitter.im/ResearchObject/ResearchObject)
